option(ENABLE_SANITIZER_UB "Enable the undefined behaviour sanitizer" OFF)
option(ENABLE_SANITIZER_ADDRESS "Enable the address-sanitizer" OFF)
option(ENABLE_SANITIZER_MEMORY "Enable the memory-sanitizer" OFF)
if(ENABLE_SANITIZER_UB OR ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_MEMORY)
  set (_SANITIZE_OPTIONS "-g -fno-omit-frame-pointer -fno-optimize-sibling-calls")
endif()
if(ENABLE_SANITIZER_UB)
  set (_SANITIZE "${_SANITIZE} -fsanitize=undefined")
endif()
if(ENABLE_SANITIZER_ADDRESS)
  set (_SANITIZE "${_SANITIZE} -fsanitize=address")
endif()
if(ENABLE_SANITIZER_MEMORY)
  set (_SANITIZE "${_SANITIZE} -fsanitize=memory")
endif()

set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${_SANITIZE_OPTIONS} ${_SANITIZE}")
set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_SANITIZE}")
